// 立创商城(嘉立创)分类树（大类 -> 小类）—— 由 scripts/fetch_lcsc.py + gen_lcsc_ts.py 自动生成，请勿手改
// 来源：https://www.szlcsc.com 首页内嵌 catalogList。id 为嘉立创 catalogId（null = 立创未给 id 的聚合分类）
// 小类参数见 lcscParams.ts（按 catalogId 索引），仅在「导入立创分类」时动态加载。
// 统计：72 大类 / 748 小类

export interface LcscParam { key: string; name: string; values: string[] }
export interface LcscMinor { seq: number; id: number | null; name: string }
export interface LcscMajor { seq: number; id: number | null; name: string; children: LcscMinor[] }

export const LCSC_CATEGORIES: LcscMajor[] = [
  { seq: 1, id: 312, name: "电容", children: [
    { seq: 1, id: 313, name: "贴片电容(MLCC)" },
    { seq: 2, id: 431, name: "直插独石电容(MLCC)" },
    { seq: 3, id: 418, name: "贴片型铝电解电容" },
    { seq: 4, id: 315, name: "直插铝电解电容" },
    { seq: 5, id: 11182, name: "牛角型电解电容" },
    { seq: 6, id: 11164, name: "螺栓型铝电解电容" },
    { seq: 7, id: 314, name: "钽电容" },
    { seq: 8, id: 927, name: "固态电容" },
    { seq: 9, id: 477, name: "安规电容" },
    { seq: 10, id: 430, name: "直插瓷片电容" },
    { seq: 11, id: 970, name: "超级电容器" },
    { seq: 12, id: 11087, name: "排容" },
    { seq: 13, id: 554, name: "聚丙烯膜电容(CBB)" },
    { seq: 14, id: 13377, name: "锂离子电容" },
    { seq: 15, id: 982, name: "薄膜电容" },
    { seq: 16, id: 552, name: "可调电容" },
    { seq: 17, id: 11023, name: "氧化铌电容" },
    { seq: 18, id: 11191, name: "纸介质电容" },
    { seq: 19, id: 11192, name: "云母和PTFE电容" },
    { seq: 20, id: 11193, name: "硅电容" },
    { seq: 21, id: 13478, name: "固液混合铝电解电容器" },
    { seq: 22, id: 14292, name: "盘式电容" },
  ]},
  { seq: 2, id: 308, name: "电阻", children: [
    { seq: 1, id: 439, name: "贴片电阻" },
    { seq: 2, id: 11239, name: "插件电阻" },
    { seq: 3, id: 909, name: "电流采样电阻 / 分流器" },
    { seq: 4, id: 311, name: "排阻" },
    { seq: 5, id: 11081, name: "铝壳 / 瓷管电阻" },
    { seq: 6, id: 520, name: "可调电阻 / 电位器" },
  ]},
  { seq: 3, id: 316, name: "电感 / 线圈 / 变压器", children: [
    { seq: 1, id: 337, name: "贴片电感" },
    { seq: 2, id: 544, name: "功率电感" },
    { seq: 3, id: 14722, name: "一体成型电感" },
    { seq: 4, id: 11245, name: "色环 / 插件电感" },
    { seq: 5, id: 944, name: "互感器" },
    { seq: 6, id: 543, name: "网口变压器" },
    { seq: 7, id: 11243, name: "无线充电线圈" },
    { seq: 8, id: 636, name: "电源变压器" },
    { seq: 9, id: 11240, name: "脉冲变压器" },
    { seq: 10, id: 11241, name: "音频变压器" },
    { seq: 11, id: 11242, name: "可调电感器" },
    { seq: 12, id: 11244, name: "电感变压器附件" },
    { seq: 13, id: 11180, name: "预售阻容感" },
  ]},
  { seq: 4, id: 470, name: "单片机 / 微控制器", children: [
    { seq: 1, id: 11329, name: "单片机(MCU / MPU / SOC)" },
    { seq: 2, id: 11328, name: "数字信号处理器(DSP / DSC)" },
    { seq: 3, id: 11330, name: "可编程逻辑器件(CPLD / FPGA)" },
    { seq: 4, id: 11181, name: "预售MCU" },
  ]},
  { seq: 5, id: 487, name: "逻辑器件", children: [
    { seq: 1, id: 11104, name: "逻辑门" },
    { seq: 2, id: 11311, name: "反相器" },
    { seq: 3, id: 11106, name: "锁存器" },
    { seq: 4, id: 11102, name: "移位寄存器" },
    { seq: 5, id: 11099, name: "触发器" },
    { seq: 6, id: 11105, name: "缓冲器 / 驱动器 / 收发器" },
    { seq: 7, id: 11098, name: "转换器 / 电平移位器" },
    { seq: 8, id: 11312, name: "数字比较器" },
    { seq: 9, id: 11103, name: "计数器 / 分频器" },
    { seq: 10, id: 11313, name: "奇偶生成器 / 校验器" },
    { seq: 11, id: 11100, name: "信号开关 / 编解码器 / 多路复用器" },
    { seq: 12, id: 11112, name: "单稳态多谐振荡器" },
    { seq: 13, id: 11310, name: "FIFO存储器" },
    { seq: 14, id: 11101, name: "特殊逻辑IC" },
  ]},
  { seq: 6, id: 319, name: "二极管", children: [
    { seq: 1, id: 321, name: "稳压二极管" },
    { seq: 2, id: 373, name: "肖特基二极管" },
    { seq: 3, id: 370, name: "通用二极管" },
    { seq: 4, id: 375, name: "整流桥" },
    { seq: 5, id: 372, name: "快恢复 / 高效率二极管" },
    { seq: 6, id: 377, name: "开关二极管" },
    { seq: 7, id: 11195, name: "超势垒整流器(SBR)" },
    { seq: 8, id: 971, name: "变容二极管" },
    { seq: 9, id: 895, name: "雪崩二极管" },
    { seq: 10, id: 379, name: "触发二极管" },
    { seq: 11, id: 13524, name: "PIN二极管" },
  ]},
  { seq: 7, id: 320, name: "三极管 / MOS管 / 晶体管", children: [
    { seq: 1, id: 381, name: "场效应管(MOSFET)" },
    { seq: 2, id: 526, name: "静电和浪涌保护(TVS / ESD)" },
    { seq: 3, id: 326, name: "三极管(BJT)" },
    { seq: 4, id: 388, name: "晶闸管(可控硅) / 模块" },
    { seq: 5, id: 562, name: "数字晶体管" },
    { seq: 6, id: 924, name: "IGBT管 / 模块" },
    { seq: 7, id: 11197, name: "半导体放电管(TSS)" },
    { seq: 8, id: 464, name: "达林顿管" },
    { seq: 9, id: 11252, name: "达林顿晶体管阵列" },
    { seq: 10, id: 11157, name: "结型场效应管(JFET)" },
    { seq: 11, id: 11219, name: "智能功率模块(IPM)" },
    { seq: 12, id: 11178, name: "预售晶体管" },
  ]},
  { seq: 8, id: 13436, name: "碳化硅(SiC)器件", children: [
    { seq: 1, id: 13393, name: "碳化硅二极管" },
    { seq: 2, id: 13459, name: "碳化硅场效应管(MOSFET)" },
    { seq: 3, id: 13460, name: "碳化硅结型场效应管(JFET)" },
    { seq: 4, id: 13461, name: "碳化硅晶闸管(可控硅)" },
  ]},
  { seq: 9, id: 13437, name: "氮化镓(GaN)器件", children: [
    { seq: 1, id: 13462, name: "氮化镓晶体管(GaN HEMT)" },
  ]},
  { seq: 10, id: 395, name: "TVS / 保险丝 / 板级保护", children: [
    { seq: 1, id: 482, name: "压敏电阻" },
    { seq: 2, id: 11196, name: "气体放电管(GDT)" },
    { seq: 3, id: 11198, name: "玻璃放电管" },
    { seq: 4, id: 11042, name: "自恢复保险丝" },
    { seq: 5, id: 11022, name: "一次性保险丝" },
    { seq: 6, id: 907, name: "汽车保险丝" },
    { seq: 7, id: 396, name: "温度保险丝(TCO)" },
    { seq: 8, id: 399, name: "保险丝座(盒)" },
  ]},
  { seq: 11, id: 380, name: "电源管理", children: [
    { seq: 1, id: 13516, name: "功率因数校正(PFC)控制器" },
    { seq: 2, id: 13517, name: "同步整流控制器" },
    { seq: 3, id: 13518, name: "快充协议芯片" },
    { seq: 4, id: 13519, name: "理想二极管 / ORing控制器" },
    { seq: 5, id: 13520, name: "电源时序控制" },
    { seq: 6, id: 387, name: "线性稳压器(LDO)" },
    { seq: 7, id: 484, name: "DC-DC电源芯片" },
    { seq: 8, id: 483, name: "AC-DC控制器和稳压器" },
    { seq: 9, id: 486, name: "电压基准芯片" },
    { seq: 10, id: 11272, name: "电流源 / 恒流源" },
    { seq: 11, id: 611, name: "电机驱动芯片" },
    { seq: 12, id: 934, name: "监控和复位芯片" },
    { seq: 13, id: 13503, name: "漏电保护芯片" },
    { seq: 14, id: 969, name: "功率电子开关" },
    { seq: 15, id: 612, name: "电池管理" },
    { seq: 16, id: 11271, name: "以太网供电(PoE)控制器" },
    { seq: 17, id: 11314, name: "浪涌保护器" },
    { seq: 18, id: 11273, name: "无线充放电芯片" },
    { seq: 19, id: 11332, name: "LED保护" },
    { seq: 20, id: 485, name: "专业电源管理(PMIC)" },
    { seq: 21, id: 13474, name: "电荷泵" },
    { seq: 22, id: 13475, name: "隔离式DC / DC转换器" },
    { seq: 23, id: 13476, name: "隔离式栅极驱动器" },
    { seq: 24, id: 13477, name: "变压器驱动器" },
  ]},
  { seq: 12, id: 575, name: "通信接口芯片", children: [
    { seq: 1, id: 578, name: "RS-485 / RS-422芯片" },
    { seq: 2, id: 577, name: "RS232芯片" },
    { seq: 3, id: 606, name: "CAN收发器" },
    { seq: 4, id: 13496, name: "CAN控制器" },
    { seq: 5, id: 576, name: "USB转换芯片" },
    { seq: 6, id: 13499, name: "USB集线器" },
    { seq: 7, id: 11320, name: "总线转UART" },
    { seq: 8, id: 579, name: "以太网收发器" },
    { seq: 9, id: 13497, name: "以太网控制器" },
    { seq: 10, id: 13498, name: "以太网交换机" },
    { seq: 11, id: 11119, name: "LIN收发器" },
    { seq: 12, id: 11133, name: "安全验证 / 加密芯片" },
    { seq: 13, id: 618, name: "模拟开关 / 多路复用器" },
    { seq: 14, id: 11319, name: "模拟开关-特殊用途" },
    { seq: 15, id: 607, name: "LVDS芯片" },
    { seq: 16, id: 11322, name: "PCI / PCIE接口" },
    { seq: 17, id: 11113, name: "信号缓冲器 / 中继器 / 分配器" },
    { seq: 18, id: 11114, name: "I / O扩展器" },
    { seq: 19, id: 11120, name: "串行器 / 解串器" },
    { seq: 20, id: 11110, name: "电信接口IC" },
    { seq: 21, id: 11323, name: "音频接口芯片" },
    { seq: 22, id: 631, name: "视频接口芯片" },
    { seq: 23, id: 11111, name: "其他接口" },
    { seq: 24, id: 11179, name: "预售芯片" },
  ]},
  { seq: 13, id: 493, name: "时钟和定时", children: [
    { seq: 1, id: 499, name: "实时时钟(RTC)" },
    { seq: 2, id: 13470, name: "555定时器 / 计时器" },
    { seq: 3, id: 11108, name: "时钟缓冲器 / 驱动器 / 分配器" },
    { seq: 4, id: 11109, name: "时钟发生器 / 频率合成器 / PLL" },
    { seq: 5, id: 11324, name: "时钟消抖" },
    { seq: 6, id: 11325, name: "定时器 / 计时器" },
    { seq: 7, id: 11326, name: "时钟延迟" },
    { seq: 8, id: 11327, name: "时钟提取和数据恢复" },
    { seq: 9, id: 13471, name: "网络时钟同步(SyncE,IEEE 1588)" },
    { seq: 10, id: 13489, name: "时钟倍频器" },
    { seq: 11, id: 11107, name: "专用时钟 / 计时" },
  ]},
  { seq: 14, id: 365, name: "连接器", children: [
    { seq: 1, id: 11068, name: "线对板针座" },
    { seq: 2, id: 11067, name: "胶壳(线对板 / 线对线)" },
    { seq: 3, id: 11070, name: "胶壳端子" },
    { seq: 4, id: 644, name: "排针" },
    { seq: 5, id: 645, name: "排母" },
    { seq: 6, id: 11355, name: "汽车连接器" },
    { seq: 7, id: 961, name: "IDC刺破式连接器(牛角 / 简牛)" },
    { seq: 8, id: 13422, name: "Micro-Match 连接器" },
    { seq: 9, id: 920, name: "FFC连接线(柔性扁平线缆)" },
    { seq: 10, id: 545, name: "FFC / FPC连接器" },
    { seq: 11, id: 960, name: "板对板与背板连接器" },
    { seq: 12, id: 13423, name: "DIN41612连接器" },
    { seq: 13, id: 369, name: "USB连接器" },
    { seq: 14, id: 11001, name: "HDMI连接器" },
    { seq: 15, id: 13419, name: "DisplayPort(DP)连接器" },
    { seq: 16, id: 630, name: "D-Sub / VGA连接器" },
    { seq: 17, id: 928, name: "DVI连接器" },
    { seq: 18, id: 13420, name: "IEEE 1394 / 火线连接器" },
    { seq: 19, id: 11071, name: "插拔式接线端子" },
    { seq: 20, id: 11140, name: "螺钉式接线端子" },
    { seq: 21, id: 432, name: "弹簧式接线端子" },
    { seq: 22, id: 11073, name: "栅栏式接线端子" },
    { seq: 23, id: 13410, name: "布线快速连接式接线端子" },
    { seq: 24, id: 366, name: "IC / 晶体管插座" },
    { seq: 25, id: 11072, name: "RF射频同轴连接器" },
    { seq: 26, id: 13424, name: "馈电 / 射频绝缘子" },
    { seq: 27, id: 590, name: "音频连接器(耳机)" },
    { seq: 28, id: 13425, name: "莲花接口 / RCA连接器" },
    { seq: 29, id: 637, name: "SIM卡连接器" },
    { seq: 30, id: 11334, name: "SD卡 / 存储卡连接器" },
    { seq: 31, id: 449, name: "以太网连接器(RJ45 RJ11)" },
    { seq: 32, id: 13416, name: "PCI / PCIe连接器" },
    { seq: 33, id: 13417, name: "硬盘连接器(SAS / SATA / M.2)" },
    { seq: 34, id: 13418, name: "内存条连接器(DDR)" },
    { seq: 35, id: 13415, name: "光模块连接器" },
    { seq: 36, id: 11083, name: "金手指连接器" },
    { seq: 37, id: 557, name: "DC电源连接器" },
    { seq: 38, id: 13421, name: "AC电源连接器" },
    { seq: 39, id: 462, name: "纽扣与条形电池连接器" },
    { seq: 40, id: 13412, name: "刀片 / 弹片接触电池连接器" },
    { seq: 41, id: 901, name: "光纤连接器" },
    { seq: 42, id: 646, name: "短路帽 / 跳线帽" },
    { seq: 43, id: 13411, name: "插针 / 插孔" },
    { seq: 44, id: 11511, name: "Pogo Pin弹簧探针连接器" },
    { seq: 45, id: 11040, name: "测试点 / 测试环" },
    { seq: 46, id: 648, name: "圆形(线缆)连接器" },
    { seq: 47, id: 13414, name: "圆形DIN连接器" },
    { seq: 48, id: 13413, name: "XLR(卡侬)连接器" },
    { seq: 49, id: 11034, name: "连接器附件" },
    { seq: 50, id: 11161, name: "光伏(太阳能板)连接器" },
    { seq: 51, id: 11079, name: "连接器外壳" },
    { seq: 52, id: 11177, name: "预售连接器" },
  ]},
  { seq: 15, id: 13644, name: "端子", children: [
    { seq: 1, id: 13648, name: "圆形端子" },
    { seq: 2, id: 13649, name: "窥口端子" },
    { seq: 3, id: 13650, name: "叉型端子" },
    { seq: 4, id: 13651, name: "钩型端子" },
    { seq: 5, id: 13652, name: "针型端子" },
    { seq: 6, id: 13653, name: "片型端子" },
    { seq: 7, id: 13654, name: "管型端子" },
    { seq: 8, id: 13655, name: "管型裸端头" },
    { seq: 9, id: 13656, name: "中间对接端子" },
    { seq: 10, id: 13657, name: "焊锡环端子" },
    { seq: 11, id: 13658, name: "插片插簧端子" },
    { seq: 12, id: 13659, name: "子弹形端子" },
    { seq: 13, id: 13660, name: "压线扣" },
    { seq: 14, id: 13661, name: "压线帽 / 闭端子" },
    { seq: 15, id: 13662, name: "免破线接线夹" },
    { seq: 16, id: 11512, name: "PCB焊接端子" },
    { seq: 17, id: 13664, name: "焊接插片端子" },
    { seq: 18, id: 13665, name: "方形铜端子" },
  ]},
  { seq: 16, id: 423, name: "按键 / 开关", children: [
    { seq: 1, id: 427, name: "轻触开关" },
    { seq: 2, id: 426, name: "行程开关" },
    { seq: 3, id: 425, name: "按键开关" },
    { seq: 4, id: 11275, name: "直键开关" },
    { seq: 5, id: 11276, name: "钮子开关" },
    { seq: 6, id: 424, name: "船型开关" },
    { seq: 7, id: 854, name: "滑动开关" },
    { seq: 8, id: 429, name: "拨码开关" },
    { seq: 9, id: 13466, name: "旋转编码开关" },
    { seq: 10, id: 943, name: "旋转编码器" },
    { seq: 11, id: 11061, name: "旋转开关" },
    { seq: 12, id: 13467, name: "拨轮开关" },
    { seq: 13, id: 13468, name: "多向开关" },
    { seq: 14, id: 13469, name: "操纵杆 / 导航开关" },
    { seq: 15, id: 11126, name: "专用开关" },
    { seq: 16, id: 11148, name: "机械键盘轴" },
    { seq: 17, id: 11018, name: "锅仔片" },
    { seq: 18, id: 11066, name: "开关配件 / 盖帽" },
    { seq: 19, id: 434, name: "多功能开关" },
  ]},
  { seq: 17, id: 601, name: "ADC / DAC / 数据转换", children: [
    { seq: 1, id: 614, name: "模数转换芯片ADC" },
    { seq: 2, id: 615, name: "数模转换芯片DAC" },
    { seq: 3, id: 619, name: "电能计量芯片" },
    { seq: 4, id: 620, name: "数字电位器" },
    { seq: 5, id: 11296, name: "模拟前端(AFE)" },
    { seq: 6, id: 861, name: "直接数字频率合成(DDS)" },
    { seq: 7, id: 11293, name: "RMS-DC转换器" },
    { seq: 8, id: 11294, name: "V / F和F / V转换芯片" },
    { seq: 9, id: 11038, name: "触摸屏控制器" },
    { seq: 10, id: 11295, name: "ADC / DAC-专用型" },
  ]},
  { seq: 18, id: 986, name: "射频芯片 / 天线", children: [
    { seq: 1, id: 11298, name: "RF调制器和解调器" },
    { seq: 2, id: 11299, name: "射频前端芯片" },
    { seq: 3, id: 11300, name: "射频功率放大器" },
    { seq: 4, id: 11301, name: "可调谐滤波器" },
    { seq: 5, id: 11302, name: "RF功分器 / 合路器" },
    { seq: 6, id: 912, name: "天线" },
    { seq: 7, id: 11331, name: "射频连接线" },
    { seq: 8, id: 542, name: "无线收发芯片" },
    { seq: 9, id: 980, name: "射频开关" },
    { seq: 10, id: 981, name: "射频卡芯片" },
    { seq: 11, id: 11019, name: "RF衰减器" },
    { seq: 12, id: 10987, name: "RF放大器" },
    { seq: 13, id: 599, name: "射频低噪声放大器" },
    { seq: 14, id: 11037, name: "RF耦合器" },
    { seq: 15, id: 10988, name: "RF混频器" },
    { seq: 16, id: 10989, name: "RF检波器" },
    { seq: 17, id: 11078, name: "双工器" },
    { seq: 18, id: 11128, name: "巴伦(balun)" },
    { seq: 19, id: 11166, name: "RF其它IC和模块" },
  ]},
  { seq: 19, id: 450, name: "光电器件", children: [
    { seq: 1, id: 528, name: "发光二极管 / LED" },
    { seq: 2, id: 11290, name: "紫外线LED(UVLED)" },
    { seq: 3, id: 11289, name: "COB光源" },
    { seq: 4, id: 639, name: "红外发射管" },
    { seq: 5, id: 11291, name: "光电晶体管" },
    { seq: 6, id: 11174, name: "红外遥控接收头(IRM)" },
    { seq: 7, id: 451, name: "光电二极管" },
    { seq: 8, id: 11292, name: "激光二极管" },
    { seq: 9, id: 11132, name: "光纤收发器" },
    { seq: 10, id: 975, name: "IrDA红外收发模块" },
    { seq: 11, id: 958, name: "光电附件" },
    { seq: 12, id: 13483, name: "RGB LED" },
    { seq: 13, id: 13484, name: "RGB LED(内置IC)" },
    { seq: 14, id: 457, name: "槽型光电开关(光电晶体管输出)" },
    { seq: 15, id: 11278, name: "反射式光电开关" },
  ]},
  { seq: 20, id: 582, name: "数码管驱动 / LED驱动", children: [
    { seq: 1, id: 583, name: "LED驱动" },
    { seq: 2, id: 11285, name: "数码管驱动" },
    { seq: 3, id: 584, name: "LCD驱动" },
    { seq: 4, id: 11287, name: "OLED驱动" },
    { seq: 5, id: 11286, name: "VFD驱动" },
    { seq: 6, id: 11129, name: "照明驱动" },
    { seq: 7, id: 11274, name: "激光驱动" },
  ]},
  { seq: 21, id: 13434, name: "光耦", children: [
    { seq: 1, id: 13394, name: "栅极驱动光耦" },
    { seq: 2, id: 11288, name: "逻辑输出光耦" },
    { seq: 3, id: 351, name: "晶体管输出光耦" },
    { seq: 4, id: 931, name: "可控硅输出光耦" },
    { seq: 5, id: 919, name: "固态继电器(MOS输出)" },
    { seq: 6, id: 11297, name: "固态继电器(可控硅输出)" },
  ]},
  { seq: 22, id: 13435, name: "显示屏", children: [
    { seq: 1, id: 11141, name: "OLED显示屏" },
    { seq: 2, id: 11142, name: "LCD显示屏" },
    { seq: 3, id: 642, name: "LED点阵屏" },
    { seq: 4, id: 11144, name: "VFD显示屏" },
    { seq: 5, id: 532, name: "LED数码管" },
    { seq: 6, id: 13458, name: "墨水屏" },
  ]},
  { seq: 23, id: 10991, name: "磁珠 / 滤波器 / EMI优化", children: [
    { seq: 1, id: 527, name: "磁珠" },
    { seq: 2, id: 640, name: "共模滤波器" },
    { seq: 3, id: 10997, name: "馈通电容滤波器" },
    { seq: 4, id: 11060, name: "EMC滤波器" },
    { seq: 5, id: 10994, name: "陶瓷滤波器" },
    { seq: 6, id: 11058, name: "钳位滤波器" },
    { seq: 7, id: 11059, name: "有源滤波器" },
    { seq: 8, id: 11057, name: "EMI滤波器(RC,LC网络)" },
    { seq: 9, id: 11247, name: "晶体滤波器" },
    { seq: 10, id: 11249, name: "噪音抑制 / 磁性片" },
    { seq: 11, id: 11248, name: "开关电容滤波器" },
    { seq: 12, id: 10995, name: "RF滤波器" },
    { seq: 13, id: 10996, name: "声表面波滤波器(SAW)" },
  ]},
  { seq: 24, id: 348, name: "振荡器 / 谐振器", children: [
    { seq: 1, id: 13525, name: "扩频振荡器" },
    { seq: 2, id: 537, name: "无源晶振" },
    { seq: 3, id: 364, name: "有源晶振" },
    { seq: 4, id: 530, name: "陶瓷谐振器(无源)" },
    { seq: 5, id: 13490, name: "热敏谐振器(无源)" },
    { seq: 6, id: 11257, name: "SAW振荡器(有源)" },
    { seq: 7, id: 529, name: "SAW谐振器(无源)" },
    { seq: 8, id: 11255, name: "温度补偿晶体振荡器(TCXO)" },
    { seq: 9, id: 11256, name: "恒温晶体振荡器(OCXO)" },
    { seq: 10, id: 11254, name: "压控晶体振荡器(VCXO)" },
    { seq: 11, id: 11303, name: "压控振荡器(VCO)" },
    { seq: 12, id: 13480, name: "压控温补振荡器(VCTXO)" },
    { seq: 13, id: 13473, name: "数控振荡器(DCO)" },
    { seq: 14, id: 11183, name: "预编程振荡器" },
  ]},
  { seq: 25, id: 500, name: "存储器", children: [
    { seq: 1, id: 502, name: "EEPROM" },
    { seq: 2, id: 501, name: "NOR FLASH" },
    { seq: 3, id: 11266, name: "NAND FLASH" },
    { seq: 4, id: 11267, name: "eMMC" },
    { seq: 5, id: 860, name: "非易失性存储器(ROM)" },
    { seq: 6, id: 11268, name: "随机存取存储器(RAM)" },
    { seq: 7, id: 503, name: "静态随机存取存储器(SRAM)" },
    { seq: 8, id: 11269, name: "动态随机存取存储器(DRAM)" },
    { seq: 9, id: 11043, name: "同步动态随机存取内存(SDRAM)" },
    { seq: 10, id: 893, name: "DDR SDRAM" },
    { seq: 11, id: 504, name: "铁电存储器(FRAM)" },
    { seq: 12, id: 13491, name: "UFS" },
    { seq: 13, id: 13492, name: "SSRAM(同步静态)" },
    { seq: 14, id: 13493, name: "PSRAM(伪静态)" },
    { seq: 15, id: 13494, name: "nvSRAM(掉电保持)" },
    { seq: 16, id: 13495, name: "iButton纽扣状存储器" },
    { seq: 17, id: 858, name: "字库芯片" },
    { seq: 18, id: 11263, name: "存储器控制器" },
    { seq: 19, id: 11264, name: "FPGA配置用存储器" },
    { seq: 20, id: 11265, name: "多芯片封装存储器" },
  ]},
  { seq: 26, id: 513, name: "传感器", children: [
    { seq: 1, id: 11046, name: "压力传感器" },
    { seq: 2, id: 11047, name: "传感器模块" },
    { seq: 3, id: 11153, name: "力传感器与测压元件" },
    { seq: 4, id: 11498, name: "心率传感器" },
    { seq: 5, id: 12445, name: "流量传感器" },
    { seq: 6, id: 13386, name: "差压传感器" },
    { seq: 7, id: 13387, name: "PM2.5传感器" },
    { seq: 8, id: 13388, name: "气体流量传感器" },
    { seq: 9, id: 13389, name: "VOC传感器" },
    { seq: 10, id: 13627, name: "电容传感IC" },
    { seq: 11, id: 435, name: "NTC热敏电阻" },
    { seq: 12, id: 541, name: "PTC热敏电阻" },
    { seq: 13, id: 11024, name: "温控开关" },
    { seq: 14, id: 585, name: "温度传感器" },
    { seq: 15, id: 11281, name: "振动传感器" },
    { seq: 16, id: 587, name: "图像传感器" },
    { seq: 17, id: 551, name: "光敏电阻" },
    { seq: 18, id: 11277, name: "槽型光电开关(逻辑输出)" },
    { seq: 19, id: 923, name: "环境光传感器" },
    { seq: 20, id: 11093, name: "光纤 / 激光传感器" },
    { seq: 21, id: 902, name: "触摸芯片" },
    { seq: 22, id: 11123, name: "位置传感器" },
    { seq: 23, id: 588, name: "姿态传感器 / 陀螺仪" },
    { seq: 24, id: 922, name: "温湿度传感器" },
    { seq: 25, id: 11044, name: "气体传感器" },
    { seq: 26, id: 11279, name: "液位传感器" },
    { seq: 27, id: 11283, name: "人体感应传感器" },
    { seq: 28, id: 11146, name: "超声波收发器" },
    { seq: 29, id: 11284, name: "接近传感器" },
    { seq: 30, id: 11092, name: "专用传感器" },
  ]},
  { seq: 27, id: 13433, name: "信号隔离器件", children: [
    { seq: 1, id: 581, name: "数字隔离器" },
    { seq: 2, id: 11259, name: "隔离式放大器" },
    { seq: 3, id: 13438, name: "隔离式RS485 / 422收发器" },
    { seq: 4, id: 13439, name: "隔离式CAN收发器" },
    { seq: 5, id: 13440, name: "隔离式I2C" },
    { seq: 6, id: 13441, name: "隔离式ADC" },
    { seq: 7, id: 13442, name: "隔离DI / DO" },
    { seq: 8, id: 13443, name: "光耦仿真器(可替换光耦)" },
    { seq: 9, id: 13444, name: "隔离式USB芯片" },
    { seq: 10, id: 13445, name: "隔离式LVDS缓冲器" },
    { seq: 11, id: 13446, name: "隔离式比较器" },
    { seq: 12, id: 13447, name: "隔离式RS-232收发器" },
    { seq: 13, id: 13448, name: "隔离式SPI" },
    { seq: 14, id: 13449, name: "隔离式ADC(带电源)" },
    { seq: 15, id: 13450, name: "隔离式SPI(带电源)" },
    { seq: 16, id: 13451, name: "隔离式USB芯片(带电源)" },
    { seq: 17, id: 13452, name: "隔离式RS-232收发器(带电源)" },
    { seq: 18, id: 13453, name: "隔离式放大器(带电源)" },
    { seq: 19, id: 13454, name: "数字隔离器(带电源)" },
    { seq: 20, id: 13455, name: "隔离式RS485 / 422收发器(带电源)" },
    { seq: 21, id: 13456, name: "隔离式I2C(带电源)" },
    { seq: 22, id: 13457, name: "隔离式CAN收发器(带电源)" },
    { seq: 23, id: 13479, name: "隔离-固态继电器" },
  ]},
  { seq: 28, id: 11304, name: "继电器", children: [
    { seq: 1, id: 531, name: "功率继电器" },
    { seq: 2, id: 11305, name: "信号继电器" },
    { seq: 3, id: 11306, name: "磁保持继电器" },
    { seq: 4, id: 11307, name: "汽车继电器" },
    { seq: 5, id: 11308, name: "簧片继电器" },
    { seq: 6, id: 11121, name: "继电器插座及配件" },
    { seq: 7, id: 13482, name: "高频 / RF继电器" },
  ]},
  { seq: 29, id: 385, name: "音频器件 / 振动马达", children: [
    { seq: 1, id: 11251, name: "蜂鸣片" },
    { seq: 2, id: 386, name: "蜂鸣器" },
    { seq: 3, id: 538, name: "扬声器 / 喇叭" },
    { seq: 4, id: 539, name: "咪头 / 麦克风" },
    { seq: 5, id: 11250, name: "MEMS麦克风" },
    { seq: 6, id: 906, name: "振动马达" },
  ]},
  { seq: 30, id: 11220, name: "功能模块", children: [
    { seq: 1, id: 11230, name: "音视频模块" },
    { seq: 2, id: 11231, name: "电机驱动模块" },
    { seq: 3, id: 959, name: "其他模块" },
  ]},
  { seq: 31, id: 938, name: "物联网 / 通信模块", children: [
    { seq: 1, id: 11048, name: "USB转换模块" },
    { seq: 2, id: 11221, name: "RFID模块" },
    { seq: 3, id: 11222, name: "2G / 3G / 4G / 5G模块" },
    { seq: 4, id: 11223, name: "LoRa模块" },
    { seq: 5, id: 11224, name: "ZigBee模块" },
    { seq: 6, id: 11225, name: "蓝牙模块" },
    { seq: 7, id: 11226, name: "CAN总线模块" },
    { seq: 8, id: 11227, name: "RS485总线模块" },
    { seq: 9, id: 11228, name: "RS232总线模块" },
    { seq: 10, id: 11229, name: "以太网模块" },
    { seq: 11, id: 939, name: "WiFi模块" },
    { seq: 12, id: 940, name: "卫星定位模块" },
    { seq: 13, id: 941, name: "射频模块" },
  ]},
  { seq: 32, id: 515, name: "运算放大器 / 比较器", children: [
    { seq: 1, id: 516, name: "运算放大器" },
    { seq: 2, id: 517, name: "比较器" },
    { seq: 3, id: 604, name: "差分运放" },
    { seq: 4, id: 598, name: "FET输入运放" },
    { seq: 5, id: 594, name: "仪表放大器" },
    { seq: 6, id: 597, name: "精密运放" },
    { seq: 7, id: 11262, name: "可编程 / 可变增益放大器(PGA / VGA)" },
    { seq: 8, id: 11258, name: "采样 / 保持放大器" },
    { seq: 9, id: 11261, name: "电流感应放大器" },
    { seq: 10, id: 518, name: "音频功率放大器" },
    { seq: 11, id: 11260, name: "视频放大器" },
    { seq: 12, id: 11188, name: "线性 - 模拟乘法器 / 除法器" },
    { seq: 13, id: 11055, name: "特殊功能放大器" },
  ]},
  { seq: 33, id: 953, name: "开发板 / 开发工具", children: [
    { seq: 1, id: 11135, name: "开发板" },
    { seq: 2, id: 11136, name: "仿真器 / 烧录器" },
    { seq: 3, id: 534, name: "书籍" },
    { seq: 4, id: 11139, name: "洞洞板 / 面包板" },
    { seq: 5, id: 11152, name: "树莓派" },
    { seq: 6, id: 11160, name: "创客教育套件" },
  ]},
  { seq: 34, id: null, name: "工具", children: [
    { seq: 1, id: 12055, name: "焊台" },
    { seq: 2, id: 11532, name: "卷尺" },
    { seq: 3, id: 11486, name: "镊子" },
    { seq: 4, id: 14438, name: "电烙铁" },
    { seq: 5, id: 12061, name: "吸锡线" },
    { seq: 6, id: 11526, name: "吸锡器" },
    { seq: 7, id: 11547, name: "斜嘴钳" },
    { seq: 8, id: 11546, name: "剥线钳" },
    { seq: 9, id: 11543, name: "压线钳" },
    { seq: 10, id: 11542, name: "尖嘴钳" },
    { seq: 11, id: 11973, name: "水口钳" },
    { seq: 12, id: 11539, name: "热风枪" },
    { seq: 13, id: 12713, name: "发热芯" },
    { seq: 14, id: 12147, name: "工具箱" },
    { seq: 15, id: 12062, name: "吸烟仪" },
    { seq: 16, id: 12060, name: "熔锡炉" },
    { seq: 17, id: 12057, name: "离子风机" },
    { seq: 18, id: 12112, name: "热熔胶棒" },
    { seq: 19, id: 12642, name: "热熔胶枪" },
    { seq: 20, id: 12059, name: "热风拆焊台" },
    { seq: 21, id: 12162, name: "防静电刷子" },
    { seq: 22, id: 12785, name: "防静电镊子" },
    { seq: 23, id: 11921, name: "内六角扳手" },
    { seq: 24, id: 11540, name: "一字螺丝批" },
    { seq: 25, id: 11541, name: "十字螺丝批" },
    { seq: 26, id: 11598, name: "螺丝批套装" },
    { seq: 27, id: 11537, name: "电烙铁套装" },
    { seq: 28, id: 11984, name: "电钻 / 起子机" },
    { seq: 29, id: 11900, name: "电子维修套装" },
    { seq: 30, id: 11998, name: "抛光机 / 磨光机" },
  ]},
  { seq: 35, id: null, name: "仪器仪表", children: [
    { seq: 1, id: 12714, name: "电桥" },
    { seq: 2, id: 13581, name: "表笔" },
    { seq: 3, id: 13563, name: "万用表" },
    { seq: 4, id: 13585, name: "示波器" },
    { seq: 5, id: 12593, name: "钳形表" },
    { seq: 6, id: 12325, name: "噪音计" },
    { seq: 7, id: 12697, name: "照度计" },
    { seq: 8, id: 12701, name: "显微镜" },
    { seq: 9, id: 12700, name: "功率计" },
    { seq: 10, id: 12595, name: "测温仪" },
    { seq: 11, id: 12303, name: "测试夹" },
    { seq: 12, id: 11199, name: "电子负载" },
    { seq: 13, id: 12326, name: "温湿度计" },
    { seq: 14, id: 12299, name: "电流探头" },
    { seq: 15, id: 12301, name: "高压探头" },
    { seq: 16, id: 12316, name: "信号发生器" },
    { seq: 17, id: 11200, name: "逻辑分析仪" },
    { seq: 18, id: 12696, name: "网络寻线仪" },
    { seq: 19, id: 13151, name: "电阻测量仪" },
    { seq: 20, id: 13572, name: "安规测试仪" },
    { seq: 21, id: 12661, name: "红外热成像仪" },
    { seq: 22, id: 12327, name: "超声波清洗机" },
    { seq: 23, id: 12659, name: "直流稳压电源" },
    { seq: 24, id: 12703, name: "转速表 / 转速计" },
  ]},
  { seq: 36, id: null, name: "耗材", children: [
    { seq: 1, id: 12728, name: "焊锡球" },
    { seq: 2, id: 12514, name: "瞬干胶" },
    { seq: 3, id: 12517, name: "导热胶" },
    { seq: 4, id: 12512, name: "结构胶" },
    { seq: 5, id: 12518, name: "耐水砂纸" },
    { seq: 6, id: 12509, name: "锡丝 / 锡线" },
    { seq: 7, id: 12510, name: "锡膏 / 锡浆" },
    { seq: 8, id: 11448, name: "金属管件接头" },
    { seq: 9, id: 11525, name: "助焊剂 / 助焊膏" },
    { seq: 10, id: 12507, name: "导热片 / 导热帽" },
    { seq: 11, id: 12506, name: "固定座 / 固定夹" },
    { seq: 12, id: 12511, name: "通用胶水 / 胶棒" },
    { seq: 13, id: 11495, name: "导热 / 导电材料" },
    { seq: 14, id: 13371, name: "金属制品*SMT铜片" },
    { seq: 15, id: 12797, name: "晶体管垫片 / 尼龙垫片" },
  ]},
  { seq: 37, id: null, name: "工控", children: [
    { seq: 1, id: null, name: "电源" },
    { seq: 2, id: null, name: "开关" },
    { seq: 3, id: null, name: "传感器" },
    { seq: 4, id: null, name: "控制与交互" },
    { seq: 5, id: null, name: "驱动与电机" },
    { seq: 6, id: null, name: "编码器" },
    { seq: 7, id: null, name: "声光信号" },
    { seq: 8, id: null, name: "磁环磁珠" },
    { seq: 9, id: null, name: "功能模块" },
    { seq: 10, id: null, name: "电气辅料" },
  ]},
  { seq: 38, id: null, name: "散热", children: [
    { seq: 1, id: null, name: "散热风扇" },
    { seq: 2, id: null, name: "散热材料" },
    { seq: 3, id: null, name: "通风设备" },
    { seq: 4, id: null, name: "散热器件" },
  ]},
  { seq: 39, id: null, name: "低压配电", children: [
    { seq: 1, id: null, name: "继电器" },
    { seq: 2, id: null, name: "断路器" },
    { seq: 3, id: null, name: "电路保护" },
    { seq: 4, id: null, name: "配电系统" },
    { seq: 5, id: null, name: "接触器" },
    { seq: 6, id: null, name: "电容器" },
  ]},
  { seq: 40, id: null, name: "电池", children: [
    { seq: 1, id: null, name: "纽扣电池" },
    { seq: 2, id: null, name: "电池连接器" },
    { seq: 3, id: null, name: "柱状电池" },
    { seq: 4, id: null, name: "方形电池" },
    { seq: 5, id: null, name: "软包电池" },
    { seq: 6, id: null, name: "蓄电池" },
  ]},
  { seq: 41, id: null, name: "线缆", children: [
    { seq: 1, id: null, name: "电子线缆" },
    { seq: 2, id: null, name: "电线电缆" },
  ]},
  { seq: 42, id: null, name: "线束", children: [
    { seq: 1, id: null, name: "基础线束" },
    { seq: 2, id: null, name: "线束组件" },
    { seq: 3, id: null, name: "线束管理" },
  ]},
  { seq: 43, id: null, name: "仪器仪表", children: [
    { seq: 1, id: null, name: "电气测量" },
    { seq: 2, id: null, name: "工程测绘" },
    { seq: 3, id: null, name: "工业检测" },
    { seq: 4, id: null, name: "环境测试" },
    { seq: 5, id: null, name: "综合测试" },
    { seq: 6, id: null, name: "仪器配件" },
    { seq: 7, id: null, name: "网络通信" },
    { seq: 8, id: null, name: "声光测试" },
    { seq: 9, id: null, name: "其它测试仪" },
  ]},
  { seq: 44, id: null, name: "工业连接器", children: [
    { seq: 1, id: null, name: "工业连接器" },
  ]},
  { seq: 45, id: null, name: "五金", children: [
    { seq: 1, id: null, name: "电子五金" },
    { seq: 2, id: null, name: "弹簧探针" },
    { seq: 3, id: null, name: "轴承" },
    { seq: 4, id: null, name: "锁具" },
    { seq: 5, id: null, name: "建筑五金" },
  ]},
  { seq: 46, id: null, name: "紧固", children: [
    { seq: 1, id: null, name: "螺母" },
    { seq: 2, id: null, name: "螺柱" },
    { seq: 3, id: null, name: "螺丝" },
    { seq: 4, id: null, name: "内六角螺钉" },
    { seq: 5, id: null, name: "十字机螺钉" },
    { seq: 6, id: null, name: "十字自攻钉" },
    { seq: 7, id: null, name: "梅花槽螺钉" },
    { seq: 8, id: null, name: "螺栓" },
    { seq: 9, id: null, name: "螺杆" },
    { seq: 10, id: null, name: "组合件" },
    { seq: 11, id: null, name: "销 / 键" },
    { seq: 12, id: null, name: "铆钉类" },
    { seq: 13, id: null, name: "膨胀系列" },
    { seq: 14, id: null, name: "喉箍 / 喉塞" },
    { seq: 15, id: null, name: "挡圈 / 垫圈" },
  ]},
  { seq: 47, id: null, name: "密封", children: [
    { seq: 1, id: null, name: "密封件" },
  ]},
  { seq: 48, id: null, name: "焊接", children: [
    { seq: 1, id: null, name: "焊接工具" },
    { seq: 2, id: null, name: "辅助工具" },
    { seq: 3, id: null, name: "SMT设备" },
    { seq: 4, id: null, name: "焊接耗材" },
    { seq: 5, id: null, name: "焊接配件" },
  ]},
  { seq: 49, id: null, name: "工具", children: [
    { seq: 1, id: null, name: "螺丝刀" },
    { seq: 2, id: null, name: "钳类" },
    { seq: 3, id: null, name: "切割工具" },
    { seq: 4, id: null, name: "电工工具" },
    { seq: 5, id: null, name: "绝缘工具" },
    { seq: 6, id: null, name: "扳手类" },
    { seq: 7, id: null, name: "镊子类" },
    { seq: 8, id: null, name: "敲击工具" },
    { seq: 9, id: null, name: "套筒" },
    { seq: 10, id: null, name: "夹具" },
    { seq: 11, id: null, name: "电动工具" },
    { seq: 12, id: null, name: "气动工具" },
    { seq: 13, id: null, name: "园林工具" },
    { seq: 14, id: null, name: "管道工具" },
    { seq: 15, id: null, name: "液压工具" },
    { seq: 16, id: null, name: "工具组套" },
    { seq: 17, id: null, name: "工具耗材" },
    { seq: 18, id: null, name: "汽修工具" },
    { seq: 19, id: null, name: "工具配件" },
    { seq: 20, id: null, name: "测量工具" },
    { seq: 21, id: null, name: "防爆工具" },
    { seq: 22, id: null, name: "其它工具" },
    { seq: 23, id: null, name: "机床设备" },
  ]},
  { seq: 50, id: null, name: "量具", children: [
    { seq: 1, id: null, name: "测量工具" },
    { seq: 2, id: null, name: "量尺" },
    { seq: 3, id: null, name: "量规" },
    { seq: 4, id: null, name: "指示表" },
    { seq: 5, id: null, name: "定位量具" },
    { seq: 6, id: null, name: "量具附件" },
  ]},
  { seq: 51, id: null, name: "耗材", children: [
    { seq: 1, id: null, name: "焊接耗材" },
    { seq: 2, id: null, name: "润滑耗材" },
    { seq: 3, id: null, name: "实验耗材" },
    { seq: 4, id: null, name: "板材制品" },
    { seq: 5, id: null, name: "建筑材料" },
  ]},
  { seq: 52, id: null, name: "刀具", children: [
    { seq: 1, id: null, name: "钻削刀具" },
    { seq: 2, id: null, name: "螺纹刀具" },
    { seq: 3, id: null, name: "锉削刀具" },
    { seq: 4, id: null, name: "刀具刀片" },
    { seq: 5, id: null, name: "其它刀具" },
  ]},
  { seq: 53, id: null, name: "磨具", children: [
    { seq: 1, id: null, name: "砂磨材料" },
    { seq: 2, id: null, name: "磨削设备" },
    { seq: 3, id: null, name: "磨具配件" },
  ]},
  { seq: 54, id: null, name: "数码", children: [
    { seq: 1, id: null, name: "电脑设备" },
    { seq: 2, id: null, name: "电脑外设" },
    { seq: 3, id: null, name: "电脑组件" },
    { seq: 4, id: null, name: "排插 / 面板" },
    { seq: 5, id: null, name: "3C配件" },
    { seq: 6, id: null, name: "通讯设备" },
    { seq: 7, id: null, name: "网络设备" },
    { seq: 8, id: null, name: "生活电器" },
    { seq: 9, id: null, name: "影音摄像" },
    { seq: 10, id: null, name: "会议设备" },
  ]},
  { seq: 55, id: null, name: "存储", children: [
    { seq: 1, id: null, name: "存储用品" },
    { seq: 2, id: null, name: "外接配件" },
  ]},
  { seq: 56, id: null, name: "办公", children: [
    { seq: 1, id: null, name: "书写画笔" },
    { seq: 2, id: null, name: "纸本画册" },
    { seq: 3, id: null, name: "财会用品" },
    { seq: 4, id: null, name: "文件整理" },
    { seq: 5, id: null, name: "办公工具" },
    { seq: 6, id: null, name: "装订整册" },
    { seq: 7, id: null, name: "办公设备" },
    { seq: 8, id: null, name: "打印设备" },
    { seq: 9, id: null, name: "打印耗材" },
    { seq: 10, id: null, name: "打包收纳" },
    { seq: 11, id: null, name: "户外装备" },
    { seq: 12, id: null, name: "办公日用" },
    { seq: 13, id: null, name: "会议演示" },
    { seq: 14, id: null, name: "办公家具" },
    { seq: 15, id: null, name: "厨用电器" },
    { seq: 16, id: null, name: "娱乐运动" },
    { seq: 17, id: null, name: "其它办公" },
  ]},
  { seq: 57, id: null, name: "粘胶", children: [
    { seq: 1, id: null, name: "工业胶带" },
    { seq: 2, id: null, name: "普通胶带" },
    { seq: 3, id: null, name: "结构胶" },
    { seq: 4, id: null, name: "密封胶" },
    { seq: 5, id: null, name: "工业胶" },
    { seq: 6, id: null, name: "电子胶" },
    { seq: 7, id: null, name: "瞬干胶" },
    { seq: 8, id: null, name: "修补胶" },
    { seq: 9, id: null, name: "其它粘胶" },
  ]},
  { seq: 58, id: null, name: "润滑", children: [
    { seq: 1, id: null, name: "工业润滑" },
    { seq: 2, id: null, name: "润滑设备" },
  ]},
  { seq: 59, id: null, name: "化工", children: [
    { seq: 1, id: null, name: "表面处理" },
    { seq: 2, id: null, name: "清洗防锈" },
    { seq: 3, id: null, name: "油漆涂料" },
    { seq: 4, id: null, name: "化学试剂" },
  ]},
  { seq: 60, id: null, name: "消防", children: [
    { seq: 1, id: null, name: "灭火设备" },
    { seq: 2, id: null, name: "消防器材" },
  ]},
  { seq: 61, id: null, name: "安防", children: [
    { seq: 1, id: null, name: "安防设备" },
    { seq: 2, id: null, name: "安全标识" },
    { seq: 3, id: null, name: "道路安全" },
  ]},
  { seq: 62, id: null, name: "应急", children: [
    { seq: 1, id: null, name: "应急照明" },
    { seq: 2, id: null, name: "救援用品" },
    { seq: 3, id: null, name: "急救设备" },
    { seq: 4, id: null, name: "防汛用品" },
    { seq: 5, id: null, name: "医疗 / 急救" },
  ]},
  { seq: 63, id: null, name: "劳保", children: [
    { seq: 1, id: null, name: "头部防护" },
    { seq: 2, id: null, name: "呼吸防护" },
    { seq: 3, id: null, name: "眼脸部防护" },
    { seq: 4, id: null, name: "身体防护" },
    { seq: 5, id: null, name: "静电防护" },
    { seq: 6, id: null, name: "手部防护" },
    { seq: 7, id: null, name: "足部防护" },
    { seq: 8, id: null, name: "坠落防护" },
    { seq: 9, id: null, name: "焊接防护" },
    { seq: 10, id: null, name: "其它防护" },
  ]},
  { seq: 64, id: null, name: "清洁", children: [
    { seq: 1, id: null, name: "工业擦拭" },
    { seq: 2, id: null, name: "垃圾处理" },
    { seq: 3, id: null, name: "地垫台垫" },
    { seq: 4, id: null, name: "个人清洁" },
    { seq: 5, id: null, name: "清洁设备" },
    { seq: 6, id: null, name: "清洁工具" },
  ]},
  { seq: 65, id: null, name: "照明", children: [
    { seq: 1, id: null, name: "移动照明" },
    { seq: 2, id: null, name: "室内照明" },
    { seq: 3, id: null, name: "室外照明" },
    { seq: 4, id: null, name: "照明配件" },
  ]},
  { seq: 66, id: null, name: "暖通", children: [
    { seq: 1, id: null, name: "供暖设备" },
    { seq: 2, id: null, name: "通风散热" },
    { seq: 3, id: null, name: "温湿度调节" },
  ]},
  { seq: 67, id: null, name: "管泵阀", children: [
    { seq: 1, id: null, name: "管材" },
    { seq: 2, id: null, name: "管件" },
    { seq: 3, id: null, name: "阀门" },
    { seq: 4, id: null, name: "泵" },
    { seq: 5, id: null, name: "管路辅助" },
  ]},
  { seq: 68, id: null, name: "气动件", children: [
    { seq: 1, id: null, name: "气源设备" },
    { seq: 2, id: null, name: "气动连接" },
    { seq: 3, id: null, name: "气动执行" },
  ]},
  { seq: 69, id: null, name: "搬运存储", children: [
    { seq: 1, id: null, name: "存储器具" },
    { seq: 2, id: null, name: "装卸搬运" },
    { seq: 3, id: null, name: "起重设备" },
    { seq: 4, id: null, name: "登高设备" },
    { seq: 5, id: null, name: "工位器具" },
    { seq: 6, id: null, name: "仓储设备" },
    { seq: 7, id: null, name: "货物包装" },
  ]},
  { seq: 70, id: null, name: "包装标识", children: [
    { seq: 1, id: null, name: "胶带类" },
    { seq: 2, id: null, name: "袋子类" },
    { seq: 3, id: null, name: "缠绕膜类" },
    { seq: 4, id: null, name: "打包材料" },
    { seq: 5, id: null, name: "包装设备" },
    { seq: 6, id: null, name: "捆扎材料" },
    { seq: 7, id: null, name: "标识用品" },
  ]},
  { seq: 71, id: null, name: "实验室", children: [
    { seq: 1, id: null, name: "实验仪器" },
    { seq: 2, id: null, name: "实验工具" },
    { seq: 3, id: null, name: "实验耗材" },
    { seq: 4, id: null, name: "实验器皿" },
    { seq: 5, id: null, name: "实验设备" },
  ]},
  { seq: 72, id: null, name: "机器人套件", children: [
    { seq: 1, id: null, name: "头部系统" },
    { seq: 2, id: null, name: "控制系统" },
    { seq: 3, id: null, name: "感知系统" },
    { seq: 4, id: null, name: "上肢系统" },
    { seq: 5, id: null, name: "下肢系统" },
    { seq: 6, id: null, name: "机械骨架" },
    { seq: 7, id: null, name: "执行系统" },
    { seq: 8, id: null, name: "动力能源" },
    { seq: 9, id: null, name: "热控防护" },
    { seq: 10, id: null, name: "神经网络" },
    { seq: 11, id: null, name: "控制枢纽" },
    { seq: 12, id: null, name: "维护与升级" },
  ]},
]
